### ISSUE TITLE
using docker-compose

### ISSUE THREAD

**Issue by frpz** [Mikroways/rancher-haproxy#3]
Hello,

I've install this image, and it works great when I create a stack with rancher.

But when I use docker-compose in the command line, the host is not detected and not added to the haproxy config.

```
version: '2'
services:
  testweb2:
    image: php:5.6-apache
    restart: always
    volumes:
      - ./index.php:/var/www/html/index.php
    labels:
      - io.rancher.container.network=true
      - io.rancher_haproxy.exposed_port=80
      - io.rancher_haproxy.server_names=testweb2.example.fr

```

Is there a label I have to add, or anything else I can do?
